# Generated by Django 4.0.6 on 2022-08-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('user_id', models.IntegerField()),
                ('is_superuser', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=300)),
            ],
        ),
    ]
