# Generated by Django 4.0.6 on 2022-08-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='password',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
