# Generated by Django 4.0.6 on 2022-08-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0003_userdata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='approval_status',
            field=models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected')], max_length=250),
        ),
    ]
