# Generated by Django 4.0.6 on 2022-08-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0004_alter_task_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managerdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=200)),
                ('manager_id', models.IntegerField()),
            ],
        ),
    ]
