# Generated by Django 4.0.6 on 2022-08-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0005_managerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='approval_status',
            field=models.CharField(max_length=250),
        ),
    ]
